const express = require('express')
const {logIn,getadmin,addUser,changePassword,getLocation,logOut} = require('../controller/admin.controller')
const {uploadImage,upload} =require('../controller/uploadImage')
// const getadmin = require('../controller/admin.controller')
const adminAuth =require('../middleware/adminAuth')
const router = express.Router()
const cors = require('cors')
router.use(cors())

router.post('/login',logIn)
router.post('/changeadminpassword',adminAuth,changePassword)
router.get('/getadmin',adminAuth,getadmin)
router.get('/getlocation',getLocation)
router.post('/adduser',adminAuth,addUser)
router.get('/logout',adminAuth,logOut)
module.exports = router