const express = require('express')
const router = express.Router()
const {getUser,signUp,verifyEmail,logIn,logOut,emailCheck,resendOtp}=require('../controller/user.controller')
const auth =require('../middleware/auth')
router.get('/get',auth,getUser)
router.post('/signup',signUp)
router.post('/verifyemail',verifyEmail)
router.post('/login',logIn)
router.get('/logout',auth,logOut)
router.get('/emailcheck/:email',emailCheck)
router.post('/resendotp',resendOtp)
module.exports = router 